sudo: required

matrix:
  include:
    ###################
    - language: cpp
      compiler: gcc
      os: linux
      env:
        - VARIANT=ddl
      script:
        - dlib/travis/build-and-test.sh

    ###################
    - language: cpp
      arch: arm64
      compiler: gcc
      os: linux
      env:
        - VARIANT=ddl
      script:
        - dlib/travis/build-and-test.sh
