sudo: required

matrix:
  include:
    ###################
    - language: cpp
      compiler: clang
      os: linux
      env:
        - VARIANT=test
      script:
        - dlib/travis/build-and-test.sh

    ###################
    - language: cpp
      compiler: clang
      os: linux
      env:
        - VARIANT=examples
      script:
        - dlib/travis/build-and-test.sh

    ###################
    - language: cpp
      compiler: gcc
      os: linux
      env:
        - VARIANT=test
      script:
        - dlib/travis/build-and-test.sh

    ###################
    - language: cpp
      compiler: gcc
      os: linux
      env:
        - VARIANT=dlib_all_source_cpp
      script:
        - dlib/travis/build-and-test.sh

    ###################
    - language: cpp
      compiler: gcc
      os: linux
      env:
        - VARIANT=examples
      script:
        - dlib/travis/build-and-test.sh

